export const parseCSVLineNew = (line, isHeader = false) => {
  const columns = line.split(",");
  let [
    NO_PERFORMA,
    CABANG,
    HRSO,
    TGL_INVOICE,
    BRANCHID,
    BRANCHCODE,
    NO_INVOICE,
    PARTY_NUMBER,
    PARTY_NAME,
    DAYS,
    PERIODE,
    QTY,
    KODE_PRODUCT,
    PRODUK,
    UOM,
    HNA,
    SALES,
    IDSUP,
    NO_FDK,
    SALES_TYPE,
    TYPE_ORDER,
    PO_NUMBER,
    ONGKIR,
    ATTR1,
  ] = columns;
  return isHeader
    ? null
    : {
        NO_PERFORMA,
        CABANG,
        HRSO,
        TGL_INVOICE,
        BRANCHID,
        BRANCHCODE,
        NO_INVOICE,
        PARTY_NUMBER,
        PARTY_NAME: PARTY_NAME ? PARTY_NAME.replace(/"/g, "") : null,
        DAYS,
        PERIODE,
        QTY,
        KODE_PRODUCT,
        PRODUK,
        UOM,
        HNA,
        SALES,
        IDSUP,
        NO_FDK,
        SALES_TYPE: SALES_TYPE ? SALES_TYPE.replace(/"/g, "") : null,
        TYPE_ORDER,
        PO_NUMBER,
        ONGKIR,
        ATTR1,
      };
};
