export const parseCSVLine = (line, isHeader = false) => {
  const columns = line.split(";");
  let [
    CABANG,
    BRANCHID,
    HRSO,
    NO_INVOICE,
    NO_PERFORMA,
    JENIS,
    GRUPLANG,
    KODELANG,
    SITE_NUMBER,
    PARTY_NAME,
    NAMALANG,
    ALMTLANG,
    KLSOUT,
    DAYS,
    BLN,
    PERIODE,
    KODE_PRODUCT,
    PRODUK,
    UOM,
    KEMASAN,
    PRINCIPAL,
    QTY,
    HNA,
    SALES,
    CLASSPROD,
    KETKLASP,
    IDSUP,
    ON_MPI,
    ONMPI,
    ON_PRIN,
    ONPRINC,
    ASKES,
    BONUS,
    PERBONUS,
    NO_FDK,
    NOMORF,
    TGLF,
    NO_DPL,
    OFF_MPI,
    OFF_PRINC,
    CNTARIK,
    CITY,
    TGL_INVOICE,
    BRANCHCODE,
    YEAR,
    SALES_TYPE,
    INTERFACE_LINE_ATTRIBUTE5,
    TYPE_ORDER,
    PO_NUMBER,
    ONGKIR,
    PRICE_ID,
    ATTR1,
    ATTR2,
    CN_TARIK,
    OFFMPI,
    OFFPRINC,
  ] = columns;

  if (/^\d+$/.test(NO_INVOICE)) {
    NO_INVOICE = Number(NO_INVOICE.replace(/,/g, ""));
  }
  if (/^\d+$/.test(NO_PERFORMA)) {
    NO_PERFORMA = Number(NO_PERFORMA.replace(/,/g, ""));
  }

  return isHeader
    ? null
    : {
        CABANG,
        BRANCHID,
        HRSO,
        NO_INVOICE:
          NO_INVOICE && typeof NO_INVOICE === "string"
            ? Number(NO_INVOICE.replace(/,/g, ""))
            : null,
        NO_PERFORMA:
          NO_PERFORMA && typeof NO_PERFORMA === "string"
            ? Number(NO_PERFORMA.replace(/,/g, ""))
            : null,
        JENIS,
        GRUPLANG,
        KODELANG,
        SITE_NUMBER,
        PARTY_NAME,
        NAMALANG,
        ALMTLANG,
        KLSOUT,
        DAYS,
        BLN,
        PERIODE,
        KODE_PRODUCT,
        PRODUK,
        UOM,
        KEMASAN,
        PRINCIPAL,
        QTY,
        HNA,
        SALES,
        CLASSPROD,
        KETKLASP,
        IDSUP,
        ON_MPI,
        ONMPI,
        ON_PRIN,
        ONPRINC,
        ASKES,
        BONUS,
        PERBONUS,
        NO_FDK,
        NOMORF,
        TGLF,
        NO_DPL,
        OFF_MPI,
        OFF_PRINC,
        CNTARIK,
        CITY,
        TGL_INVOICE,
        BRANCHCODE,
        YEAR,
        SALES_TYPE,
        INTERFACE_LINE_ATTRIBUTE5,
        TYPE_ORDER,
        PO_NUMBER,
        ONGKIR,
        PRICE_ID,
        ATTR1,
        ATTR2,
        CN_TARIK,
        OFFMPI,
        OFFPRINC,
      };
};
